# Generated by Django 4.1 on 2022-09-08 10:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bussiness_line', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=50)),
                ('person', models.CharField(max_length=500)),
                ('mod_time', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
            ],
            options={
                'verbose_name': '基础数据',
                'verbose_name_plural': '基础数据',
                'db_table': 'magic_team_base',
            },
        ),
    ]
